# Hexo Configuration
# See: http://hexo.io/docs/configuration.html

# Site
title: sudo ISL
subtitle: We build the Internet
description: ISL Engineering Blog
author: ISL
language: en
timezone: UTC
url: https://sudo.isl.co/
root: /
permalink: :year/:month/:title/
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
theme: isl

# Writing
new_post_name: :year-:month-:day-:title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true

# Date / Time format
# See: http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Plugins
feed:
  type: atom
  path: atom.xml
  limit: 20

node_sass:
  includePaths:
    - node_modules/foundation-sites/scss/
  outputStyle: expanded
  precision: 10
  sourceComments: false

